# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'WordsFactory' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WordsFactory
	pod 'Alamofire'

end
